DATA_FOLDER = '/src/data'
RESULTS_FOLDER = '/src/results'
TENSORBOARD_BASE_FOLDER = '/src/results/tensorboard'
INDICES_FILE = 'Data_Entry_2017.csv'

WEIGHT_PATH = "{}_weights.best.hdf5".format('xray_class')

MIN_CASES = 1000
IMG_SIZE = (299, 299)
LEARNING_RATE = 0.0005
SYNTHETIC_BATCH_SIZE = 256
BATCH_SIZE = 32
ACCUMULATION_STEPS = int(SYNTHETIC_BATCH_SIZE / BATCH_SIZE)
VALIDATION_BATCH_SIZE = BATCH_SIZE*2
EPOCHS = 100
STEPS_PER_EPOCH = 1000
EARLY_STOPPING = 5
WORKERS = 8
